import { Montserrat } from 'next/font/google'
import '../css/styles.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const montserrat = Montserrat({ weight: ['400', '700'], subsets: ['latin'] })

export const metadata = {
  title: 'B.One Concept',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
